name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o cash-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o cash-linux-arm64 main.go

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o cash-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o cash-darwin-arm64 main.go

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o cash-windows-amd64.exe main.go

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cash-linux-amd64
            cash-linux-arm64
            cash-darwin-amd64
            cash-darwin-arm64
            cash-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
